GET http://localhost:5004
###
GET http://localhost:5004/all?month=09

###
GET http://localhost:5004/statistics?month=07

###

GET http://localhost:5004/barchart?month=04
###

GET http://localhost:5004/piechart?month=05
###

GET  http://localhost:5004/combinedData?month=06
###